services:
  - type: web
    name: open-data-center-api
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production

