"""Add foreign key relationships between data_centers, metadata, and change_history

Revision ID: 56600d27b509
Revises: 7e8fa26bae5b
Create Date: 2025-12-29 22:05:45.166479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56600d27b509'
down_revision: Union[str, None] = '7e8fa26bae5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'data_centers_metadata', 'data_centers', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_centers_metadata', type_='foreignkey')
    # ### end Alembic commands ###
