"""Initial migration

Revision ID: 7e8fa26bae5b
Revises: 
Create Date: 2025-12-29 22:02:46.267889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8fa26bae5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=False)
    op.create_table('data_centers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dc_name', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('date_added', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_centers_id'), 'data_centers', ['id'], unique=False)
    op.create_table('data_centers_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('development_stage', sa.Text(), nullable=True),
    sa.Column('facility_status', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('installed_power_capacity_mw', sa.Float(), nullable=True),
    sa.Column('installed_area_sq_ft', sa.Float(), nullable=True),
    sa.Column('tenants', sa.Text(), nullable=True),
    sa.Column('connectivity_providers', sa.Text(), nullable=True),
    sa.Column('operation_start_date', sa.String(), nullable=True),
    sa.Column('update_date_time', sa.String(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('num_buildings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_centers_metadata_id'), 'data_centers_metadata', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_table('data_center_change_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_center_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_email', sa.String(), nullable=False),
    sa.Column('changed_by_name', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_center_id'], ['data_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_center_change_history_data_center_id'), 'data_center_change_history', ['data_center_id'], unique=False)
    op.create_index(op.f('ix_data_center_change_history_id'), 'data_center_change_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_center_change_history_id'), table_name='data_center_change_history')
    op.drop_index(op.f('ix_data_center_change_history_data_center_id'), table_name='data_center_change_history')
    op.drop_table('data_center_change_history')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_data_centers_metadata_id'), table_name='data_centers_metadata')
    op.drop_table('data_centers_metadata')
    op.drop_index(op.f('ix_data_centers_id'), table_name='data_centers')
    op.drop_table('data_centers')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
